### ISSUE TITLE
How to get a fixed string value format

### ISSUE THREAD

**Issue by chengm204** [jk-jeon/dragonbox#50] opened 2023-11-24 07:04 UTC
For example, 
```
constexpr int buffer_length = 1 + // for '\0'
                  jkj::dragonbox::max_output_string_length<jkj::dragonbox::ieee754_binary64>;
char buffer[buffer_length];
double d{980528.1478392933};
char* end_ptr = jkj::dragonbox::to_chars(price, buffer);
std::cout << buffer << std::endl;
```
I got "9.805281478392933E5", but I want "980528.1478392933";

**Comment by jk-jeon** [comment] 2023-11-24 08:00
Thanks, but this is a duplicate of https://github.com/jk-jeon/dragonbox/issues/35.
Closing.

**Closed by jk-jeon** 2023-11-24 08:00 UTC
